Repository My-Power-STN39M-Hopefully/django-good-egg-backend, pull requests merged in 2020-09, with the labels that each got.

#46 Setup basic django project
  .gitignore
  Pipfile
  Pipfile.lock
  README.md
  good_egg/__init__.py
  good_egg/admin.py
  good_egg/apps.py
  good_egg/migrations/__init__.py
  good_egg/models.py
  good_egg/tests.py
  good_egg/views.py
  good_egg_django/__init__.py
  good_egg_django/asgi.py
  good_egg_django/settings.py
  good_egg_django/urls.py
  good_egg_django/wsgi.py
  manage.py
  settings.sql
Labels: enhancement

#45 Add Django rest framework
  Pipfile
  Pipfile.lock
  good_egg/templates/landing_page.html
  good_egg/urls.py
  good_egg/views.py
  good_egg_django/settings.py
  good_egg_django/urls.py
Labels: enhancement

#63 [DEV OPS] Create Project migration script for issues and prs
  .github/workflows/sync-issues-prs-to-proejct.yml
Labels: dev-ops

#68 Added models views and controllers for Force Officers and Incident
  good_egg/admin.py
  good_egg/migrations/0001_initial.py
  good_egg/migrations/0002_auto_20200909_1001.py
  good_egg/models.py
  good_egg/serializers.py
  good_egg/templates/landing_page.html
  good_egg/urls.py
  good_egg/views.py
  good_egg_django/settings.py
Labels: models

#69 [FEATURE] Add CORS
  good_egg_django/settings.py
Labels: enhancement

#72 [FEATURE] Add user authorization via api
  Pipfile
  Pipfile.lock
  good_egg/serializers.py
  good_egg/urls.py
  good_egg/views.py
  good_egg_django/settings.py
Labels: enhancement

#40 Create Incident model and CRUD controller
  good_egg/templates/landing_page.html
  good_egg/urls.py
  good_egg/views.py
  good_egg_django/settings.py
Labels: models

#39 Create Officer model and CRUD controller
  Pipfile
  Pipfile.lock
  good_egg/models.py
  good_egg/templates/landing_page.html
  good_egg/urls.py
  good_egg/views.py
Labels: models

#88 [FEATURE] Cookie sent to browser not found
  Pipfile
  good_egg/migrations/0004_auto_20200913_1420.py
  good_egg/migrations/0005_auto_20200913_1421.py
  good_egg/migrations/0006_auto_20200913_1426.py
  good_egg/models.py
  good_egg/serializers.py
  good_egg/templates/landing_page.html
  good_egg/urls.py
  good_egg/views.py
  good_egg_django/settings.py
  good_egg_django/urls.py
  users/serializers.py
  users/urls.py
  users/views.py
Labels: enhancement
